import { ComponentMetadata } from './types';
import {
	LayoutGrid,
	Megaphone,
	MessageSquare,
	Zap,
	Users,
	Grid3x3,
	DollarSign,
	Mail,
	Image as ImageIcon,
	BarChart3,
	HelpCircle,
	Users2,
	Briefcase,
	Send,
	GitBranch,
	Table,
} from 'lucide-react';

export const componentMetadata: ComponentMetadata[] = [
	{
		type: 'navbar',
		name: 'Navigation Bar',
		description: 'Header navigation with links and branding',
		icon: 'LayoutGrid',
		variantCount: 3,
	},
	{
		type: 'hero',
		name: 'Hero Section',
		description: 'Eye-catching header with main messaging',
		icon: 'Megaphone',
		variantCount: 4,
	},
	{
		type: 'features',
		name: 'Features',
		description: 'Showcase product or service features',
		icon: 'Grid3x3',
		variantCount: 3,
	},
	{
		type: 'testimonials',
		name: 'Testimonials',
		description: 'Customer reviews and feedback',
		icon: 'MessageSquare',
		variantCount: 3,
	},
	{
		type: 'pricing',
		name: 'Pricing',
		description: 'Pricing tables and plans',
		icon: 'DollarSign',
		variantCount: 3,
	},
	{
		type: 'cta',
		name: 'Call to Action',
		description: 'Encourage user action with compelling CTAs',
		icon: 'Zap',
		variantCount: 3,
	},
	{
		type: 'contact',
		name: 'Contact Form',
		description: 'Forms for user inquiries and messages',
		icon: 'Mail',
		variantCount: 3,
	},
	{
		type: 'gallery',
		name: 'Gallery',
		description: 'Image and media showcases',
		icon: 'ImageIcon',
		variantCount: 3,
	},
	{
		type: 'stats',
		name: 'Statistics',
		description: 'Display key metrics and numbers',
		icon: 'BarChart3',
		variantCount: 3,
	},
	{
		type: 'faq',
		name: 'FAQ',
		description: 'Frequently asked questions',
		icon: 'HelpCircle',
		variantCount: 3,
	},
	{
		type: 'team',
		name: 'Team',
		description: 'Showcase team members',
		icon: 'Users2',
		variantCount: 3,
	},
	{
		type: 'logos',
		name: 'Logo Showcase',
		description: 'Display partner or client logos',
		icon: 'Briefcase',
		variantCount: 3,
	},
	{
		type: 'newsletter',
		name: 'Newsletter',
		description: 'Email subscription forms',
		icon: 'Send',
		variantCount: 3,
	},
	{
		type: 'process',
		name: 'Process Steps',
		description: 'Visual workflow or step-by-step guide',
		icon: 'GitBranch',
		variantCount: 3,
	},
	{
		type: 'comparison',
		name: 'Comparison Table',
		description: 'Side-by-side feature comparisons',
		icon: 'Table',
		variantCount: 3,
	},
	{
		type: 'footer',
		name: 'Footer',
		description: 'Column footer with links and social',
		icon: 'Layout',
		variantCount: 3,
		defaultStyles: {},
	},
	{
		type: 'spacer',
		name: 'Spacer',
		description: 'Add vertical spacing between components',
		icon: 'MoveVertical',
		variantCount: 3,
		defaultStyles: {},
	},
];

// Helper function to get icon component by name
export const getIconComponent = (iconName: string) => {
	const icons: Record<string, any> = {
		LayoutGrid,
		Megaphone,
		MessageSquare,
		Zap,
		Users,
		Grid3x3,
		DollarSign,
		Mail,
		ImageIcon,
		BarChart3,
		HelpCircle,
		Users2,
		Briefcase,
		Send,
		GitBranch,
		Table,
	};
	return icons[iconName] || LayoutGrid;
};

export const defaultStyles: Record<string, any> = {
	fontFamily: 'Inter, sans-serif',
	fontSize: '1rem',
	fontColor: '#000000',
	bgColor: '#ffffff',
	margin: { top: 0, right: 0, bottom: 0, left: 0 },
	padding: { top: 16, right: 16, bottom: 16, left: 16 },
	shadow: 'none' as const,
};
