import React, { useState, useRef, useMemo } from 'react';
import Link from 'next/link';
import { NextSeo } from 'next-seo';
import ToolJsonLd from '@/components/seo/ToolJsonLd';
import ToolFaqSection from '@/components/tools/ToolFaqSection';
import {
	Download,
	Upload,
	Copy,
	Check,
	FileCode,
	ShieldAlert,
	Sparkles,
	Sliders,
	Eye,
} from 'lucide-react';
import {
	optimizeSvgString,
	convertSvgToReactJsx,
	convertSvgToReactNative,
	convertSvgToDataUri,
	DEFAULT_SVG_OPTIONS,
	SvgOptimizeOptions,
} from '@/lib/svgHelper';

const SVG_FAQS = [
	{
		question: 'How does SVG minification reduce file size?',
		answer: 'It removes editor metadata, XML comments, unused namespaces, and redundant whitespace, while rounding coordinate decimals to lower file weight without visual distortion.',
	},
	{
		question: 'What is the benefit of converting SVG to React JSX or React Native?',
		answer: 'Converting to JSX or React Native components replaces XML attributes (like stroke-width and class) with camelCase equivalents (strokeWidth and className) and formats the markup into ready-to-use functional components.',
	},
	{
		question: 'Are my graphic vectors processed on a server?',
		answer: 'No. All vector DOM parsing, coordinate precision trimming, and conversions occur entirely client-side in your web browser.',
	},
];

type ExportTab = 'svg' | 'jsx' | 'reactNative' | 'dataUri';
type BgMode = 'checker' | 'white' | 'dark';

const SAMPLE_SVGS = [
	{
		label: 'Geometric Star',
		svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <!-- Generated by Vector Studio -->
  <metadata><desc>Sample Star Polygon</desc></metadata>
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#3b82f6" />
      <stop offset="100%" stop-color="#8b5cf6" />
    </linearGradient>
  </defs>
  <circle cx="50.00000" cy="50.00000" r="42.50000" fill="url(#grad1)" />
  <polygon points="50.00000,24.12345 58.12345,40.54321 76.12345,43.23456 63.12345,55.87654 66.12345,73.87654 50.00000,65.34567 33.87654,73.87654 36.87654,55.87654 23.87654,43.23456 41.87654,40.54321" fill="#ffffff" />
</svg>`,
	},
	{
		label: 'App Shield Badge',
		svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" width="120" height="120" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
  <!-- Sketch layer metadata -->
  <g sketch:type="MSLayerGroup" id="ShieldLayer">
    <path d="M60.00000 12.00000 L95.00000 28.00000 C95.00000 68.00000 60.00000 105.00000 60.00000 105.00000 C60.00000 105.00000 25.00000 68.00000 25.00000 28.00000 Z" fill="#10b981" />
    <path d="M48.00000 58.00000 L56.00000 66.00000 L74.00000 48.00000" fill="none" stroke="#ffffff" stroke-width="6.00000" stroke-linecap="round" stroke-linejoin="round" />
  </g>
</svg>`,
	},
	{
		label: 'Sparkle Icon',
		svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <!-- Clean spark vector -->
  <path d="M32.00000 4.00000 C32.00000 19.46400 44.53600 32.00000 60.00000 32.00000 C44.53600 32.00000 32.00000 44.53600 32.00000 60.00000 C32.00000 44.53600 19.46400 32.00000 4.00000 32.00000 C19.46400 32.00000 32.00000 19.46400 32.00000 4.00000 Z" fill="#f59e0b" />
</svg>`,
	},
];

export default function SVGOptimizer() {
	const [svgInput, setSvgInput] = useState(SAMPLE_SVGS[0].svg);
	const [options, setOptions] =
		useState<SvgOptimizeOptions>(DEFAULT_SVG_OPTIONS);
	const [exportTab, setExportTab] = useState<ExportTab>('svg');
	const [bgMode, setBgMode] = useState<BgMode>('checker');
	const [pngScale, setPngScale] = useState<number>(2);
	const [componentName, setComponentName] = useState<string>('CustomIcon');
	const [copied, setCopied] = useState(false);
	const [] = useState<string | null>(null);

	const previewRef = useRef<HTMLDivElement>(null);

	// Validate input XML
	const parseError = useMemo(() => {
		if (!svgInput.trim()) return null;
		if (typeof window === 'undefined') return null;
		try {
			const parser = new DOMParser();
			const xmlDoc = parser.parseFromString(svgInput, 'image/svg+xml');
			const parserError = xmlDoc.querySelector('parsererror');
			if (parserError) {
				return 'Malformed XML: check closing tags and quotes.';
			}
			return null;
		} catch {
			return 'Unable to parse SVG XML.';
		}
	}, [svgInput]);

	// Optimized SVG string
	const optimizedSvg = useMemo(() => {
		if (parseError || !svgInput.trim()) return '';
		return optimizeSvgString(svgInput, options);
	}, [svgInput, options, parseError]);

	// Size calculation
	const origBytes = useMemo(() => new Blob([svgInput]).size, [svgInput]);
	const optBytes = useMemo(
		() => new Blob([optimizedSvg]).size,
		[optimizedSvg],
	);
	const savingsPct = useMemo(() => {
		if (!origBytes || !optBytes) return 0;
		const diff = origBytes - optBytes;
		return Math.max(0, Math.round((diff / origBytes) * 100));
	}, [origBytes, optBytes]);

	// Current tab code output
	const activeOutput = useMemo(() => {
		if (!optimizedSvg) return '';
		switch (exportTab) {
			case 'svg':
				return optimizedSvg;
			case 'jsx':
				return convertSvgToReactJsx(optimizedSvg, componentName, true);
			case 'reactNative':
				return convertSvgToReactNative(optimizedSvg, componentName);
			case 'dataUri':
				return convertSvgToDataUri(optimizedSvg, false);
			default:
				return optimizedSvg;
		}
	}, [optimizedSvg, exportTab, componentName]);

	const copyToClipboard = () => {
		if (!activeOutput) return;
		navigator.clipboard.writeText(activeOutput);
		setCopied(true);
		setTimeout(() => setCopied(false), 2000);
	};

	const downloadFile = (content: string, filename: string, mime: string) => {
		const blob = new Blob([content], { type: mime });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	};

	const downloadPNG = () => {
		if (!optimizedSvg || typeof window === 'undefined') return;
		try {
			const parser = new DOMParser();
			const xmlDoc = parser.parseFromString(
				optimizedSvg,
				'image/svg+xml',
			);
			const svgElement = xmlDoc.querySelector('svg');
			if (!svgElement) return;

			let width = 300;
			let height = 300;

			if (
				svgElement.viewBox &&
				svgElement.viewBox.baseVal &&
				svgElement.viewBox.baseVal.width
			) {
				width = svgElement.viewBox.baseVal.width;
				height = svgElement.viewBox.baseVal.height;
			} else {
				width = parseInt(svgElement.getAttribute('width') || '300', 10);
				height = parseInt(
					svgElement.getAttribute('height') || '300',
					10,
				);
			}

			const canvas = document.createElement('canvas');
			canvas.width = width * pngScale;
			canvas.height = height * pngScale;
			const ctx = canvas.getContext('2d');
			if (!ctx) return;

			const svgBlob = new Blob([optimizedSvg], {
				type: 'image/svg+xml;charset=utf-8',
			});
			const url = URL.createObjectURL(svgBlob);
			const img = new Image();

			img.onload = () => {
				ctx.scale(pngScale, pngScale);
				ctx.drawImage(img, 0, 0);
				const pngUrl = canvas.toDataURL('image/png');
				const a = document.createElement('a');
				a.href = pngUrl;
				a.download = `${componentName.toLowerCase()}-${pngScale}x.png`;
				document.body.appendChild(a);
				a.click();
				document.body.removeChild(a);
				URL.revokeObjectURL(url);
			};
			img.src = url;
		} catch (err) {
			console.error('Failed to export SVG to PNG:', err);
		}
	};

	const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
		const file = e.target.files?.[0];
		if (!file) return;

		const reader = new FileReader();
		reader.onload = (event) => {
			if (typeof event.target?.result === 'string') {
				setSvgInput(event.target.result);
			}
		};
		reader.readAsText(file);
	};

	return (
		<>
			<NextSeo
				title="SVG Code Optimizer & React JSX Exporter | Client-Side - Joey Jazwinski"
				description="Minify raw SVG vectors, strip editor metadata and namespaces, round path coordinates, and export as clean React JSX or React Native SVG components."
				canonical="https://joeyjazwinski.com/developer-tools/svg-optimizer"
				openGraph={{
					title: 'SVG Code Optimizer & React JSX Exporter | Client-Side - Joey Jazwinski',
					description:
						'Minify raw SVG vectors, strip editor metadata and namespaces, round path coordinates, and export as clean React JSX or React Native SVG components.',
					url: 'https://joeyjazwinski.com/developer-tools/svg-optimizer',
					type: 'website',
					images: [
						{
							url: 'https://joeyjazwinski.com/ogimage.png',
							width: 1200,
							height: 630,
							alt: 'SVG Code Optimizer and Exporter',
						},
					],
				}}
				twitter={{
					handle: '@JoeyJazwinski',
					site: '@JoeyJazwinski',
					cardType: 'summary_large_image',
				}}
			/>
			<ToolJsonLd
				name="SVG Code Optimizer & React JSX Exporter"
				description="Minify raw SVG vectors, strip editor metadata and namespaces, round path coordinates, and export as clean React JSX or React Native SVG components."
				url="https://joeyjazwinski.com/developer-tools/svg-optimizer"
				category="DesignApplication"
				faqs={SVG_FAQS}
			/>
			<main className="bg-background pt-32 pb-16 px-4 sm:px-6 lg:px-8 text-foreground">
				<div className="max-w-6xl mx-auto space-y-8">
					<div>
						<Link
							href="/developer-tools"
							className="inline-flex items-center text-xs font-semibold text-muted-foreground hover:text-primary transition mb-4"
						>
							← Back to all developer tools
						</Link>
					</div>

					{/* Header */}
					<div className="text-center space-y-4 max-w-2xl mx-auto">
						<div className="inline-flex p-3 rounded-2xl bg-primary/10 text-primary border border-primary/20">
							<FileCode className="w-8 h-8" />
						</div>
						<h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl bg-linear-to-r from-primary via-cyan-500 to-blue-500 bg-clip-text text-transparent">
							SVG Optimizer & Exporter
						</h1>
						<p className="text-muted-foreground text-lg">
							Strip editor namespaces, round coordinates, preview
							vectors, and export to React JSX, React Native, or
							high-res PNG.
						</p>
					</div>

					{/* Presets and Upload Bar */}
					<div className="flex flex-wrap items-center justify-between gap-3 p-3 bg-card border border-border/80 rounded-2xl shadow-sm">
						<div className="flex flex-wrap items-center gap-2">
							<span className="text-xs font-semibold text-muted-foreground mr-1 flex items-center gap-1">
								<Sparkles className="w-3.5 h-3.5 text-primary" />
								Samples:
							</span>
							{SAMPLE_SVGS.map((s, idx) => (
								<button
									key={idx}
									onClick={() => setSvgInput(s.svg)}
									className="px-3 py-1.5 text-xs font-medium rounded-lg bg-secondary/80 hover:bg-secondary border border-border text-foreground transition"
								>
									{s.label}
								</button>
							))}
						</div>

						<label className="inline-flex items-center gap-1.5 text-xs bg-primary text-primary-foreground font-semibold px-3.5 py-1.5 rounded-lg cursor-pointer hover:opacity-95 transition">
							<Upload className="w-3.5 h-3.5" />
							Upload SVG
							<input
								type="file"
								accept=".svg"
								onChange={handleFileUpload}
								className="hidden"
							/>
						</label>
					</div>

					{/* Metric Strip */}
					<div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
						<div className="p-4 rounded-xl bg-card border border-border">
							<div className="text-xs text-muted-foreground">
								Original Size
							</div>
							<div className="text-lg font-mono font-bold text-foreground mt-1">
								{origBytes} B
							</div>
						</div>
						<div className="p-4 rounded-xl bg-card border border-border">
							<div className="text-xs text-muted-foreground">
								Optimized Size
							</div>
							<div className="text-lg font-mono font-bold text-emerald-500 mt-1">
								{optBytes} B
							</div>
						</div>
						<div className="p-4 rounded-xl bg-card border border-border">
							<div className="text-xs text-muted-foreground">
								Savings
							</div>
							<div className="text-lg font-mono font-bold text-primary mt-1">
								{savingsPct > 0 ? `-${savingsPct}%` : '0%'}
							</div>
						</div>
						<div className="p-4 rounded-xl bg-card border border-border flex items-center justify-between">
							<div>
								<div className="text-xs text-muted-foreground">
									Status
								</div>
								<div className="text-sm font-semibold text-foreground mt-1">
									{parseError ? 'Error' : 'Ready'}
								</div>
							</div>
							<div
								className={`w-3 h-3 rounded-full ${
									parseError
										? 'bg-rose-500'
										: 'bg-emerald-500 animate-pulse'
								}`}
							/>
						</div>
					</div>

					{/* Main Workbench */}
					<div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
						{/* Left: Input & Optimization Rules */}
						<div className="lg:col-span-6 space-y-6">
							{/* Editor */}
							<div className="bg-card border border-border rounded-2xl p-6 shadow-xl space-y-4">
								<div className="flex justify-between items-center pb-2 border-b border-border/50">
									<h2 className="text-sm font-bold uppercase tracking-wider text-muted-foreground">
										Raw SVG Input
									</h2>
									<button
										onClick={() => setSvgInput('')}
										className="text-xs text-muted-foreground hover:text-foreground"
									>
										Clear
									</button>
								</div>

								<textarea
									id="svg-input-textarea"
									aria-label="SVG XML source code input"
									value={svgInput}
									onChange={(e) =>
										setSvgInput(e.target.value)
									}
									className="w-full h-64 p-3.5 rounded-xl border border-border bg-background font-mono text-xs focus:outline-none focus:ring-2 focus:ring-primary transition resize-none shadow-inner"
									placeholder="<svg ...>...</svg>"
								/>

								{parseError && (
									<div className="flex items-start gap-2 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs text-rose-600 dark:text-rose-400 font-mono">
										<ShieldAlert className="w-4 h-4 shrink-0 mt-0.5" />
										<span>{parseError}</span>
									</div>
								)}
							</div>

							{/* Optimizer Settings */}
							<div className="bg-card border border-border rounded-2xl p-6 shadow-xl space-y-4">
								<h3 className="text-sm font-bold flex items-center gap-2">
									<Sliders className="w-4 h-4 text-primary" />
									Optimization Rules
								</h3>

								<div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.removeComments}
											onChange={(e) =>
												setOptions({
													...options,
													removeComments:
														e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Strip Comments</span>
									</label>

									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.removeMetadata}
											onChange={(e) =>
												setOptions({
													...options,
													removeMetadata:
														e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Remove Metadata & Title</span>
									</label>

									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.removeNamespaces}
											onChange={(e) =>
												setOptions({
													...options,
													removeNamespaces:
														e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Strip Editor Namespaces</span>
									</label>

									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.removeIds}
											onChange={(e) =>
												setOptions({
													...options,
													removeIds: e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Remove Element IDs</span>
									</label>

									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.removeDimensions}
											onChange={(e) =>
												setOptions({
													...options,
													removeDimensions:
														e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Strip Fixed Width/Height</span>
									</label>

									<label className="flex items-center gap-2 cursor-pointer p-2.5 rounded-lg border border-border bg-background/50 hover:bg-secondary/40 transition">
										<input
											type="checkbox"
											checked={options.minifyWhitespace}
											onChange={(e) =>
												setOptions({
													...options,
													minifyWhitespace:
														e.target.checked,
												})
											}
											className="rounded border-border text-primary focus:ring-primary"
										/>
										<span>Minify Whitespace</span>
									</label>
								</div>

								{/* Decimal rounding slider */}
								<div className="p-3 rounded-xl border border-border bg-background/50 space-y-2">
									<div className="flex justify-between items-center text-xs">
										<label className="flex items-center gap-2 font-medium cursor-pointer">
											<input
												type="checkbox"
												checked={options.roundDecimals}
												onChange={(e) =>
													setOptions({
														...options,
														roundDecimals:
															e.target.checked,
													})
												}
												className="rounded border-border text-primary focus:ring-primary"
											/>
											<span>Round Path Decimals</span>
										</label>
										<span className="font-mono text-muted-foreground font-bold">
											{options.decimalPrecision} places
										</span>
									</div>

									{options.roundDecimals && (
										<input
											type="range"
											min={0}
											max={4}
											value={options.decimalPrecision}
											onChange={(e) =>
												setOptions({
													...options,
													decimalPrecision: parseInt(
														e.target.value,
														10,
													),
												})
											}
											className="w-full accent-primary cursor-pointer"
										/>
									)}
								</div>
							</div>
						</div>

						{/* Right: Live Preview & Formatted Export */}
						<div className="lg:col-span-6 space-y-6">
							{/* Live Canvas Preview */}
							<div className="bg-card border border-border rounded-2xl p-6 shadow-xl space-y-4">
								<div className="flex justify-between items-center pb-2 border-b border-border/50">
									<h2 className="text-sm font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
										<Eye className="w-4 h-4 text-primary" />
										Vector Preview
									</h2>

									{/* Background mode switcher */}
									<div className="flex items-center gap-1 bg-secondary/80 p-1 rounded-lg border border-border text-xs">
										<button
											onClick={() => setBgMode('checker')}
											className={`px-2 py-0.5 rounded ${
												bgMode === 'checker'
													? 'bg-card font-bold shadow-xs'
													: 'text-muted-foreground'
											}`}
										>
											Grid
										</button>
										<button
											onClick={() => setBgMode('white')}
											className={`px-2 py-0.5 rounded ${
												bgMode === 'white'
													? 'bg-card font-bold shadow-xs'
													: 'text-muted-foreground'
											}`}
										>
											Light
										</button>
										<button
											onClick={() => setBgMode('dark')}
											className={`px-2 py-0.5 rounded ${
												bgMode === 'dark'
													? 'bg-card font-bold shadow-xs'
													: 'text-muted-foreground'
											}`}
										>
											Dark
										</button>
									</div>
								</div>

								<div
									ref={previewRef}
									className={`w-full h-52 rounded-xl border border-border flex items-center justify-center p-4 overflow-hidden ${
										bgMode === 'checker'
											? 'bg-[linear-gradient(45deg,#ccc_25%,transparent_25%),linear-gradient(-45deg,#ccc_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#ccc_75%),linear-gradient(-45deg,transparent_75%,#ccc_75%)] bg-size-[16px_16px] bg-position-[0_0,0_8px,8px_-8px,-8px_0px] dark:bg-[linear-gradient(45deg,#222_25%,transparent_25%),linear-gradient(-45deg,#222_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#222_75%),linear-gradient(-45deg,transparent_75%,#222_75%)]'
											: bgMode === 'white'
												? 'bg-white'
												: 'bg-zinc-950'
									}`}
								>
									{optimizedSvg ? (
										<div
											className="max-w-full max-h-full flex items-center justify-center [&>svg]:max-h-44 [&>svg]:w-auto"
											dangerouslySetInnerHTML={{
												__html: optimizedSvg,
											}}
										/>
									) : (
										<span className="text-xs text-muted-foreground">
											Valid SVG preview will render here
										</span>
									)}
								</div>

								{/* PNG Export Controls */}
								<div className="flex items-center gap-2 pt-1">
									<select
										aria-label="PNG export resolution scale factor"
										value={pngScale}
										onChange={(e) =>
											setPngScale(
												parseInt(e.target.value, 10),
											)
										}
										className="px-3 py-2 rounded-xl border border-border bg-background text-xs font-semibold focus:ring-1 focus:ring-primary focus:outline-none cursor-pointer"
									>
										<option value={1}>1x Resolution</option>
										<option value={2}>2x Retina</option>
										<option value={3}>3x High-Res</option>
										<option value={4}>4x Ultra-Res</option>
									</select>

									<button
										onClick={downloadPNG}
										disabled={!optimizedSvg}
										className="flex-1 inline-flex items-center justify-center gap-2 py-2 px-4 rounded-xl bg-secondary hover:bg-secondary/80 border border-border text-xs font-semibold transition disabled:opacity-50"
									>
										<Download className="w-3.5 h-3.5" />
										Export PNG ({pngScale}x)
									</button>
								</div>
							</div>

							{/* Exported Code Output */}
							<div className="bg-card border border-border rounded-2xl p-6 shadow-xl space-y-4">
								<div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-border/50">
									<div className="flex flex-wrap gap-1">
										<button
											onClick={() => setExportTab('svg')}
											className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition ${
												exportTab === 'svg'
													? 'bg-primary text-primary-foreground'
													: 'text-muted-foreground hover:bg-secondary'
											}`}
										>
											SVG XML
										</button>
										<button
											onClick={() => setExportTab('jsx')}
											className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition ${
												exportTab === 'jsx'
													? 'bg-primary text-primary-foreground'
													: 'text-muted-foreground hover:bg-secondary'
											}`}
										>
											React JSX
										</button>
										<button
											onClick={() =>
												setExportTab('reactNative')
											}
											className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition ${
												exportTab === 'reactNative'
													? 'bg-primary text-primary-foreground'
													: 'text-muted-foreground hover:bg-secondary'
											}`}
										>
											React Native
										</button>
										<button
											onClick={() =>
												setExportTab('dataUri')
											}
											className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition ${
												exportTab === 'dataUri'
													? 'bg-primary text-primary-foreground'
													: 'text-muted-foreground hover:bg-secondary'
											}`}
										>
											Data URI
										</button>
									</div>

									<div className="flex items-center gap-2">
										<button
											onClick={copyToClipboard}
											disabled={!activeOutput}
											className="p-1.5 rounded-lg bg-background border border-border hover:bg-secondary text-foreground text-xs flex items-center gap-1 font-medium transition disabled:opacity-50"
										>
											{copied ? (
												<>
													<Check className="w-3.5 h-3.5 text-emerald-500" />
													<span>Copied</span>
												</>
											) : (
												<>
													<Copy className="w-3.5 h-3.5" />
													<span>Copy</span>
												</>
											)}
										</button>

										<button
											onClick={() => {
												if (exportTab === 'svg') {
													downloadFile(
														activeOutput,
														`${componentName.toLowerCase()}.svg`,
														'image/svg+xml',
													);
												} else if (
													exportTab === 'jsx'
												) {
													downloadFile(
														activeOutput,
														`${componentName}.tsx`,
														'text/plain',
													);
												} else if (
													exportTab === 'reactNative'
												) {
													downloadFile(
														activeOutput,
														`${componentName}.tsx`,
														'text/plain',
													);
												} else {
													downloadFile(
														activeOutput,
														`${componentName.toLowerCase()}.txt`,
														'text/plain',
													);
												}
											}}
											disabled={!activeOutput}
											className="p-1.5 rounded-lg bg-background border border-border hover:bg-secondary text-foreground text-xs flex items-center gap-1 font-medium transition disabled:opacity-50"
										>
											<Download className="w-3.5 h-3.5" />
											<span>Download</span>
										</button>
									</div>
								</div>

								{/* Component Name customization if JSX */}
								{(exportTab === 'jsx' ||
									exportTab === 'reactNative') && (
									<div className="flex items-center gap-2 text-xs">
										<label className="text-muted-foreground font-medium">
											Component Name:
										</label>
										<input
											type="text"
											value={componentName}
											onChange={(e) =>
												setComponentName(
													e.target.value.replace(
														/[^a-zA-Z0-9_]/g,
														'',
													),
												)
											}
											className="px-2 py-1 rounded-md border border-border bg-background font-mono text-xs focus:ring-1 focus:ring-primary focus:outline-none"
										/>
									</div>
								)}

								<pre className="w-full h-52 p-3 overflow-y-auto rounded-xl border border-border bg-background/60 font-mono text-xs shadow-inner whitespace-pre-wrap break-all">
									{activeOutput ||
										'// Optimized output appears here...'}
								</pre>
							</div>
						</div>
					</div>

					<ToolFaqSection faqs={SVG_FAQS} />
				</div>
			</main>
		</>
	);
}
