import React, { useState, useEffect, useRef } from 'react';
import { NextSeo } from 'next-seo';
import ToolJsonLd from '@/components/seo/ToolJsonLd';
import {
	Download,
	Upload,
	Copy,
	Check,
	FileCode,
	ShieldAlert,
} from 'lucide-react';

export default function SVGOptimizer() {
	const [svgInput, setSvgInput] = useState(
		'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">\n  <!-- Generated by Figma -->\n  <circle cx="50" cy="50" r="40" fill="#3b82f6" />\n  <polygon points="50,30 38,62 68,40 32,40 62,62" fill="#ffffff" />\n</svg>',
	);
	const [optimizedSvg, setOptimizedSvg] = useState('');
	const [copied, setCopied] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const previewRef = useRef<HTMLDivElement>(null);

	const optimizeSvg = (input: string) => {
		if (!input.trim()) {
			setOptimizedSvg('');
			setError(null);
			return;
		}

		try {
			// Basic XML parser check
			const parser = new DOMParser();
			const xmlDoc = parser.parseFromString(input, 'image/svg+xml');
			const parserError = xmlDoc.querySelector('parsererror');

			if (parserError) {
				setError(
					'XML Parsing Error: Make sure your SVG format is well-formed.',
				);
				setOptimizedSvg('');
				return;
			}

			setError(null);

			// Perform sanitization & optimization replacements
			let cleaned = input
				// Remove comments
				.replace(/<!--[\s\S]*?-->/g, '')
				// Remove metadata tags
				.replace(/<metadata>[\s\S]*?<\/metadata>/g, '')
				// Remove empty lines
				.replace(/^\s*[\r\n]/gm, '')
				// Remove namespace tags that are figma/sketch specific
				.replace(
					/\s(xmlns:[\w-]+|sketch:[\w-]+|inkscape:[\w-]+|sodipodi:[\w-]+)="[^"]*"/g,
					'',
				)
				// Remove redundant editor attributes
				.replace(
					/\s(custom-[\w-]+|figma:[\w-]+|sketch:[\w-]+)="[^"]*"/g,
					'',
				)
				.trim();

			setOptimizedSvg(cleaned);
		} catch (err: any) {
			setError('Optimization failed. Verify file integrity.');
			setOptimizedSvg('');
		}
	};

	useEffect(() => {
		optimizeSvg(svgInput);
	}, [svgInput]);

	const copyToClipboard = () => {
		if (!optimizedSvg) return;
		navigator.clipboard.writeText(optimizedSvg);
		setCopied(true);
		setTimeout(() => setCopied(false), 2000);
	};

	const downloadPNG = () => {
		if (!optimizedSvg) return;
		try {
			const parser = new DOMParser();
			const xmlDoc = parser.parseFromString(
				optimizedSvg,
				'image/svg+xml',
			);
			const svgElement = xmlDoc.querySelector('svg');
			if (!svgElement) return;

			// Extract dimensions or fallback to 300x300
			let width = 300;
			let height = 300;

			if (svgElement.viewBox && svgElement.viewBox.baseVal) {
				width = svgElement.viewBox.baseVal.width || 300;
				height = svgElement.viewBox.baseVal.height || 300;
			} else {
				width = parseInt(svgElement.getAttribute('width') || '300');
				height = parseInt(svgElement.getAttribute('height') || '300');
			}

			const canvas = document.createElement('canvas');
			canvas.width = width;
			canvas.height = height;
			const ctx = canvas.getContext('2d');
			if (!ctx) return;

			const svgBlob = new Blob([optimizedSvg], {
				type: 'image/svg+xml;charset=utf-8',
			});
			const url = URL.createObjectURL(svgBlob);
			const img = new Image();

			img.onload = () => {
				ctx.drawImage(img, 0, 0);
				const pngUrl = canvas.toDataURL('image/png');

				const link = document.createElement('a');
				link.href = pngUrl;
				link.download = 'vector-export.png';
				document.body.appendChild(link);
				link.click();
				document.body.removeChild(link);
				URL.revokeObjectURL(url);
			};
			img.src = url;
		} catch (err) {
			console.error('Failed to export SVG to PNG:', err);
		}
	};

	const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
		const file = e.target.files?.[0];
		if (!file) return;

		const reader = new FileReader();
		reader.onload = (event) => {
			if (event.target?.result) {
				setSvgInput(event.target.result as string);
			}
		};
		reader.readAsText(file);
	};

	return (
		<>
			<NextSeo
				title="SVG Code Optimizer & SVG Cleaner | Reduce File Size - Joey Jazwinski"
				description="Minify and optimize raw SVG code, remove metadata and useless comments, format path decimals, and preview rendering side-by-side in real time."
				canonical="https://joeyjazwinski.com/developer-tools/svg-optimizer"
				openGraph={{
					title: "SVG Code Optimizer & SVG Cleaner | Reduce File Size - Joey Jazwinski",
					description: "Minify and optimize raw SVG code, remove metadata and useless comments, format path decimals, and preview rendering side-by-side in real time.",
					url: "https://joeyjazwinski.com/developer-tools/svg-optimizer",
					type: "website",
					images: [
						{
							url: "https://joeyjazwinski.com/ogimage.png",
							width: 1200,
							height: 630,
							alt: "SVG Code Optimizer & Cleaner",
						},
					],
				}}
				twitter={{
					handle: "@JoeyJazwinski",
					site: "@JoeyJazwinski",
					cardType: "summary_large_image",
				}}
			/>
			<ToolJsonLd
				name="SVG Code Optimizer & Cleaner"
				description="Minify and optimize raw SVG code, remove metadata and useless comments, format path decimals, and preview rendering side-by-side in real time."
				url="https://joeyjazwinski.com/developer-tools/svg-optimizer"
				category="DesignApplication"
			/>
			<main className="min-h-screen bg-background pt-32 pb-16 px-4 sm:px-6 lg:px-8 text-foreground">
				<div className="max-w-6xl mx-auto space-y-12">
					{/* Header */}
					<div className="text-center space-y-4 max-w-2xl mx-auto">
						<div className="inline-flex p-3 rounded-2xl bg-primary/10 text-primary border border-primary/20">
							<FileCode className="w-8 h-8" />
						</div>
						<h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl bg-linear-to-r from-primary to-cyan-500 bg-clip-text text-transparent">
							SVG Optimizer & Exporter
						</h1>
						<p className="text-muted-foreground text-lg">
							Sanitize SVG files by removing useless metadata,
							visualize results, and rasterize them into high-res
							PNGs.
						</p>
					</div>

					{/* Workspace */}
					<div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
						{/* Editor Input */}
						<div className="lg:col-span-7 bg-card/60 backdrop-blur-xl border border-border/80 rounded-2xl p-6 sm:p-8 space-y-4 shadow-xl flex flex-col justify-between">
							<div className="space-y-4 grow">
								<div className="flex justify-between items-center pb-2 border-b border-border/50">
									<h2 className="text-lg font-bold">
										SVG XML Code
									</h2>

									<label className="flex items-center gap-1.5 text-xs bg-secondary border border-border hover:bg-secondary/80 text-muted-foreground hover:text-foreground px-2.5 py-1.5 rounded-lg cursor-pointer transition">
										<Upload className="w-3.5 h-3.5" />
										Upload File
										<input
											type="file"
											accept=".svg"
											onChange={handleFileUpload}
											className="hidden"
										/>
									</label>
								</div>

								<textarea
									id="svg-input-textarea"
									aria-label="SVG XML source code input"
									value={svgInput}
									onChange={(e) =>
										setSvgInput(e.target.value)
									}
									className="w-full h-80 p-4 rounded-xl border border-border bg-background/90 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all resize-none shadow-inner"
								/>
							</div>

							{error && (
								<div className="flex items-start gap-2.5 p-3.5 rounded-xl bg-red-500/10 border border-red-500/20 text-xs text-red-500 font-medium font-mono">
									<ShieldAlert className="w-4 h-4 shrink-0 mt-0.5" />
									<span>{error}</span>
								</div>
							)}
						</div>

						{/* Output & Preview */}
						<div className="lg:col-span-5 flex flex-col gap-6">
							{/* Live preview */}
							<div className="bg-card/60 backdrop-blur-xl border border-border/80 rounded-2xl p-6 sm:p-8 flex flex-col items-center justify-between min-h-75 shadow-xl relative">
								<h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground w-full border-b border-border/50 pb-2 mb-4">
									Vector Preview
								</h3>

								<div className="grow flex items-center justify-center py-4 w-full">
									<div
										ref={previewRef}
										className="p-4 rounded-xl border border-border bg-white shadow-inner max-w-full max-h-48 aspect-square flex items-center justify-center"
										dangerouslySetInnerHTML={{
											__html: optimizedSvg,
										}}
									/>
								</div>

								<button
									onClick={downloadPNG}
									disabled={!optimizedSvg}
									aria-label="Export SVG as high-resolution PNG image"
									className="w-full inline-flex items-center justify-center gap-2 px-5 py-3 bg-primary text-primary-foreground font-semibold rounded-xl hover:bg-primary/95 focus:outline-none focus:ring-2 focus:ring-primary transition-all disabled:opacity-50"
								>
									<Download className="w-4 h-4" />
									Export as PNG
								</button>
							</div>

							{/* Cleaned Code */}
							<div className="bg-card/60 backdrop-blur-xl border border-border/80 rounded-2xl p-6 flex flex-col shadow-xl relative">
								<div className="flex justify-between items-center pb-2 border-b border-border/50 mb-3">
									<h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
										Optimized Output
									</h3>
									{optimizedSvg && (
										<button
											onClick={copyToClipboard}
											aria-label="Copy sanitized SVG code to clipboard"
											className="p-1.5 rounded-lg bg-background border border-border hover:bg-secondary text-muted-foreground hover:text-foreground transition shadow"
										>
											{copied ? (
												<Check className="w-3.5 h-3.5 text-emerald-500" />
											) : (
												<Copy className="w-3.5 h-3.5" />
											)}
										</button>
									)}
								</div>
								<pre className="w-full h-24 p-3 overflow-y-auto rounded-xl border border-border bg-background/50 font-mono text-[10px] shadow-inner whitespace-pre-wrap break-all">
									{optimizedSvg ||
										'// Cleaned SVG will appear here...'}
								</pre>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
