import type { Metadata } from "next";
import "./globals.css";
import Breadcrumb from "../components/Breadcrumb";
import { BreadcrumbProvider } from "../components/BreadcrumbContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-background text-text">
        {/* <BreadcrumbProvider> */}
          <main>
            {/* <Breadcrumb /> */}
            {children}
          </main>
        {/* </BreadcrumbProvider> */}
      </body>
    </html>
  );
};

export default Layout;
