import { GetServerSideProps } from 'next';
import Link from 'next/link';
import { BlogPostData, getFullUrl } from '@/utils/db';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { NextSeo } from 'next-seo';
import { seoBlogs } from '@/lib/seoConfig';
import { Search, Calendar, ArrowRight } from 'lucide-react';

interface BlogIndexProps {
	posts: BlogPostData[];
}

const BlogDisclaimer: React.FC = () => (
	<p className="text-sm text-muted-foreground mt-8 text-center">
		Disclaimer: Some blog posts may contain content generated by AI.
	</p>
);

const BlogIndex: React.FC<BlogIndexProps> = ({ posts }) => {
	const [searchTerm, setSearchTerm] = useState('');

	const featuredPost = posts[0];
	const filteredPosts = posts
		.filter(
			(post) =>
				post.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
				(post.description &&
					post.description
						.toLowerCase()
						.includes(searchTerm.toLowerCase()))
		)
		.filter((post) => post !== featuredPost);

	const otherPosts = filteredPosts;

	return (
		<>
			<NextSeo {...seoBlogs} />
			<section className="py-12">
				<motion.div
					className="text-center mb-12"
					initial={{ opacity: 0, y: 20 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.5 }}
				>
					<h1 className="text-4xl font-bold mb-4">All Blogs</h1>
					<p className="text-muted-foreground text-lg mb-8">
						Discover the latest updates, tutorials, and insights
					</p>

					{/* Search Bar */}
					<div className="max-w-xl mx-auto relative">
						<Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
						<input
							type="text"
							placeholder="Search blogs..."
							value={searchTerm}
							onChange={(e) => setSearchTerm(e.target.value)}
							className="w-full pl-12 pr-4 py-3 border border-input bg-background rounded-lg focus:outline-none focus:ring-2 focus:ring-primary transition-all"
						/>
					</div>
				</motion.div>

				{/* Featured Blog */}
				{featuredPost && (
					<motion.div
						className="mb-12 p-8 bg-primary/10 border border-primary/20 rounded-xl shadow-lg"
						initial={{ opacity: 0, y: 20 }}
						whileInView={{ opacity: 1, y: 0 }}
						viewport={{ once: true }}
						whileHover={{ scale: 1.01 }}
						transition={{ duration: 0.3 }}
					>
						<div className="flex items-center gap-2 mb-3">
							<span className="px-3 py-1 bg-primary text-primary-foreground text-sm font-medium rounded-full">
								Featured
							</span>
						</div>
						<Link
							href={`/blogs/${featuredPost.slug}`}
							className="group"
						>
							<h2 className="text-3xl font-bold mb-3 group-hover:text-primary transition-colors">
								{featuredPost.title}
							</h2>
						</Link>
						<p className="text-muted-foreground mb-4 text-lg">
							{featuredPost.description}
						</p>
						<div className="flex items-center gap-4 text-sm text-muted-foreground">
							<div className="flex items-center gap-2">
								<Calendar className="w-4 h-4" />
								<span>
									{featuredPost.createdAt
										? new Date(
												featuredPost.createdAt
										  ).toLocaleDateString()
										: 'Unknown date'}
								</span>
							</div>
							<Link
								href={`/blogs/${featuredPost.slug}`}
								className="ml-auto flex items-center gap-2 text-primary font-medium hover:gap-3 transition-all"
							>
								Read More
								<ArrowRight className="w-4 h-4" />
							</Link>
						</div>
					</motion.div>
				)}

				{/* Blog Grid */}
				<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
					{otherPosts.map((post, index) => (
						<motion.div
							key={post.slug}
							className="p-6 border border-border bg-card rounded-xl shadow-md hover:shadow-xl transition-all flex flex-col"
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							viewport={{ once: true }}
							transition={{ delay: index * 0.1 }}
							whileHover={{ y: -5 }}
						>
							<Link
								href={`/blogs/${post.slug}`}
								className="group"
							>
								<h3 className="text-xl font-semibold mb-3 group-hover:text-primary transition-colors">
									{post.title}
								</h3>
							</Link>
							<p className="text-muted-foreground mb-4 flex-grow">
								{post.description}
							</p>
							<div className="flex items-center justify-between mt-auto pt-4 border-t border-border">
								<div className="flex items-center gap-2 text-sm text-muted-foreground">
									<Calendar className="w-4 h-4" />
									<span>
										{post.createdAt
											? new Date(
													post.createdAt
											  ).toLocaleDateString()
											: 'Unknown date'}
									</span>
								</div>
								<Link
									href={`/blogs/${post.slug}`}
									className="text-primary font-medium hover:underline text-sm flex items-center gap-1"
								>
									Read
									<ArrowRight className="w-4 h-4" />
								</Link>
							</div>
						</motion.div>
					))}
				</div>

				{/* No Results Message */}
				{otherPosts.length === 0 && (
					<motion.div
						className="text-center py-12"
						initial={{ opacity: 0 }}
						animate={{ opacity: 1 }}
					>
						<p className="text-muted-foreground text-lg">
							No blogs match your search criteria.
						</p>
					</motion.div>
				)}

				<BlogDisclaimer />
			</section>
		</>
	);
};

export const getServerSideProps: GetServerSideProps = async () => {
	try {
		const response = await fetch(getFullUrl('/api/getBlogPosts'), {
			method: 'GET',
			credentials: 'include',
		});
		const data = await response.json();

		return {
			props: {
				posts:
					data.blogPosts.sort((a: BlogPostData, b: BlogPostData) => {
						const dateA = a.createdAt
							? new Date(a.createdAt).getTime()
							: 0;
						const dateB = b.createdAt
							? new Date(b.createdAt).getTime()
							: 0;
						return dateB - dateA;
					}) || [],
			},
		};
	} catch (error) {
		console.error('Error fetching blog posts:', error);
		return {
			props: {
				posts: [],
			},
		};
	}
};

export default BlogIndex;
